# Generated by Django 4.1.6 on 2023-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("priPhotoDate", models.ImageField(upload_to="")),
                ("photoDate", models.ImageField(upload_to="")),
            ],
        ),
    ]
