# Generated by Django 3.2.17 on 2023-04-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_photo_photodate_alter_photo_priphotodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoDate',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='priPhotoDate',
            field=models.CharField(max_length=64),
        ),
    ]
